exports.standardNames = {
    3: "Console API",
    22: "execCommand",
    2: "Beacon",
    7: "CSSOM View Module",
    6: "CSS Object Model",
    18: "DOM",
    19: "DOM Parsing and Serialization",
    9: "Directory Upload",
    14: "DOM Level 2: Style",
    1: "Battery API",
    4: "CSS Conditional Rules Module Level 3",
    12: "DOM Level 2: Events",
    10: "DOM Level 1",
    17: "DOM Level 3: XPath",
    20: "Encoding",
    11: "DOM Level 2: Core",
    15: "DOM Level 2: Traversal and Range",
    13: "DOM Level 2: HTML",
    5: "CSS Font Loading Module Level 3",
    16: "DOM Level 3: Core",
    8: "DeviceOrientation Event",
    21: "Encrypted Media Extensions",
    76: "Non-Standard",
    32: "HTML: Web Sockets",
    31: "HTML: The canvas element",
    30: "HTML: Broadcasting",
    33: "HTML: Channel Messaging",
    41: "HTML Editing APIs",
    35: "HTML: Web Workers",
    36: "HTML: Web Storage",
    38: "HTML: History Interface",
    34: "HTML: Plugins",
    40: "HTML 5.1",
    42: "Indexed Database API",
    27: "Geolocation API Specication",
    24: "File API",
    23: "Fetch",
    29: "High Resolution Time Level 2",
    39: "HTML 5",
    25: "Fullscreen API",
    37: "HTML",
    28: "Geometry Interfaces Module Level 1",
    26: "Gamepad",
    65: "User Timing Level 2",
    60: "The Screen Orientation API",
    64: "URL",
    62: "Tracking Preference Expression",
    63: "UI Events",
    66: "Vibration API",
    67: "W3C DOM4",
    59: "Shadow DOM",
    61: "Script-based animation timing control",
    68: "Web Audio API",
    69: "Web Cryptography API",
    70: "WebGL",
    73: "XMLHttpRequest",
    72: "WebVTT",
    74: "Ambient Light Sensor API",
    71: "WebRTC",
    47: "Navigation Timing",
    46: "MediaStream Recording",
    44: "Media Capture from DOM Elements",
    43: "Media Capture and Streams",
    45: "Media Source Extensions",
    48: "Web Notifications",
    53: "Proximity Events",
    54: "Resource Timing",
    55: "Scalable Vector Graphics",
    51: "Performance Timeline Level 2",
    57: "Selectors API Level 1",
    58: "Service Workers",
    50: "Performance Timeline",
    52: "Pointer Lock",
    56: "Selection API",
    49: "Page Visibility (Second Edition)"
};